# Generated by Django 2.1.4 on 2019-01-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=200)),
                ('slug', models.CharField(help_text='Введите slug для ссылки', max_length=25)),
                ('summary', models.TextField(help_text='Введите описание статьи', max_length=1000)),
                ('image', models.ImageField(upload_to='blogs')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', '-modified_at'],
            },
        ),
    ]
