# Generated by Django 2.1.4 on 2019-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=123, upload_to='posts/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
