# Generated by Django 2.1.4 on 2019-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(help_text='Введите описание статьи'),
        ),
    ]
