# Generated by Django 2.1.4 on 2019-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, choices=[('a', 'BUSINESS'), ('b', 'MARKETING'), ('c', 'DESIGN'), ('d', 'DATABASE'), ('e', 'PROGRAM')], default='b', help_text='Выберите тип курса', max_length=1)),
                ('title', models.CharField(help_text='Введите название курса', max_length=200)),
                ('priсe', models.FloatField(help_text='Введите цену курса', max_length=10)),
                ('image', models.ImageField(upload_to='courses/%Y/%m/%d')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', '-priсe'],
            },
        ),
    ]
