# Generated by Django 2.1.4 on 2019-01-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='courses',
            field=models.ManyToManyField(default=None, help_text='Выберете курс', to='posts.Courses'),
        ),
    ]
