# Generated by Django 2.1.4 on 2019-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_subscribers_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
